"""跨层共用的结构体定义。"""

from .audit import AuditEvent
from .chat import ChatMessage
from .chunk import Chunk
from .context import EXT_MAX_TOKENS, Context
from .entity import (
    EntityBatchResult,
    EntityLinkResult,
    EntityMention,
    EntityOperation,
    EntityOpType,
    EntityRecord,
    EntityStoreFilters,
    EntityType,
    hash_entity_text,
)
from .feature import Entity, FeatureSet, Relation
from .filter import (
    MEMORY_TYPE_FILTER_FIELD,
    FilterClause,
    FilterExpr,
    FilterGroup,
    FilterLogic,
    FilterOp,
    and_merge,
    canonical_filter_field,
    evaluate,
    extract_required_equality,
    filter_field_metadata_key,
    from_dict,
    iter_clauses,
    normalize,
    validate,
)
from .memory import (
    MEMORY_KEY_PREFIX,
    T_EVENT_UNKNOWN,
    T_INVALID_OPEN,
    ContentLayers,
    DedupDecision,
    LifecycleState,
    MemoryTier,
    MemoryUnit,
    MetadataValueType,
    Modality,
    Segment,
    Temporal,
    inherited_system_metadata,
    inherited_user_metadata,
    memory_key,
)
from .memory_filter import matches_memory_unit
from .normalizer import EntityNormalizer
from .raw import MESSAGES_KEY_PREFIX, RawPayload, messages_key
from .retrieval import (
    CandidateFuser,
    ChannelError,
    ChannelEvidence,
    ParsedQuery,
    RankedStorageResult,
    RecallBatch,
    RecallChannel,
    RecallResult,
    RetrievalPipeline,
    ScoredCandidate,
    ScoredMemoryUnit,
    ScoredUnit,
)
from .retrieval_filter import (
    in_event_window,
    is_retrieval_candidate,
    matches_retrieval_filters,
    passes_lifecycle,
    valid_at,
)
from .scope import Scope, space_id_from_scope

__all__ = [
    "Scope",
    "space_id_from_scope",
    "Context",
    "EXT_MAX_TOKENS",
    "Modality",
    "MemoryTier",
    "DedupDecision",
    "LifecycleState",
    "Temporal",
    "Segment",
    "MemoryUnit",
    "MetadataValueType",
    "ContentLayers",
    "inherited_system_metadata",
    "inherited_user_metadata",
    "RawPayload",
    "Chunk",
    "Entity",
    "EntityType",
    "EntityMention",
    "EntityStoreFilters",
    "EntityRecord",
    "EntityLinkResult",
    "EntityOpType",
    "EntityOperation",
    "EntityBatchResult",
    "hash_entity_text",
    "EntityNormalizer",
    "Relation",
    "FeatureSet",
    "ChatMessage",
    "AuditEvent",
    "FilterClause",
    "FilterOp",
    "FilterLogic",
    "FilterGroup",
    "FilterExpr",
    "MEMORY_TYPE_FILTER_FIELD",
    "normalize",
    "validate",
    "canonical_filter_field",
    "filter_field_metadata_key",
    "and_merge",
    "iter_clauses",
    "evaluate",
    "extract_required_equality",
    "from_dict",
    "MEMORY_KEY_PREFIX",
    "T_INVALID_OPEN",
    "T_EVENT_UNKNOWN",
    "MESSAGES_KEY_PREFIX",
    "memory_key",
    "messages_key",
    "matches_memory_unit",
    "RecallChannel",
    "ParsedQuery",
    "ChannelEvidence",
    "ScoredUnit",
    "ScoredMemoryUnit",
    "ScoredCandidate",
    "RecallBatch",
    "RecallResult",
    "ChannelError",
    "RankedStorageResult",
    "RetrievalPipeline",
    "CandidateFuser",
    "valid_at",
    "passes_lifecycle",
    "in_event_window",
    "matches_retrieval_filters",
    "is_retrieval_candidate",
]
